Play travis
Otus-DevOps-2020-02/ivkosarev_infra pull request #1
Opened 2020-03-12 13:03 UTC by ivkosarev

2020-03-12 13:57 UTC, mrgreyves requested changes
Здравствуйте!) У вас определенно что-то пошло не так. Слишком много мусора в репозитории, нужно очистить. Возвращаю на доработку.

2020-03-13 06:27 UTC, mrgreyves requested changes
Здравствуйте!) Осталось совсем чуть-чуть. Добавил комментарий к проблемному тесту. Возвращаю в доработку.

2020-03-13 06:27 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
А вот теперь нужно починить сломавшийся тест =)

2020-03-15 12:12 UTC, ivkosarev commented
вроде получилось

пт, 13 мар. 2020 г. в 09:27, Vladimir Drozdetskiy <notifications@github.com
>:

> *@mrgreyves* requested changes on this pull request.
>
> Здравствуйте!) Осталось совсем чуть-чуть. Добавил комментарий к
> проблемному тесту. Возвращаю в доработку.
> ------------------------------
>
> In play-travis/test.py
> <https://github.com/Otus-DevOps-2020-02/ivkosarev_infra/pull/1#discussion_r392050023>
> :
>
> > @@ -0,0 +1,9 @@
>
> +import unittest
>
> +
>
> +class NumbersTest(unittest.TestCase):
>
> +
>
> +    def test_equal(self):
>
> +        self.assertEqual(1 + 1, 1)
>
>
> А вот теперь нужно починить сломавшийся тест =)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2020-02/ivkosarev_infra/pull/1#pullrequestreview-374072670>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOLE5W4UQYLFDTC2R3FSPI3RHHG4XANCNFSM4LGLZBXA>
> .
>

2020-03-15 17:34 UTC, mrgreyves approved these changes
Здравствуйте!) Вот теперь все хорошо, апрув!)

2020-04-14 12:47 UTC, merged